export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as Newsletter } from './Newsletter'
export { default as ProductSidebar } from './ProductSidebar'
export { default as ProfileSidebar } from './ProfileSidebar'
